services:
  - type: web
    name: orderqueen-login
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn oq_login:app
env:
  - CHROME_PATH=/usr/local/bin/chromium-browser
  - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
